# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: stephen-agent

jobs:
- job: DevPlan
  pool:
    name: stephen-agent
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.10.5'
    displayName: 'Installing Terraform'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      commandOptions: '-backend-config="key=terraform-prod.tfstate"'
      backendServiceArm: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
      backendAzureRmResourceGroupName: 'stephen-blob'
      backendAzureRmStorageAccountName: 'stephenstorage'
      backendAzureRmContainerName: 'stephen-blob'
      backendAzureRmKey: 'terraform-prod.tfstate'
    displayName: 'Terraform init'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-var-file=prod.tfvars'
      environmentServiceNameAzureRM: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
    displayName: 'Terraform plan'

- job: DevApply
  pool:
    name: stephen-agent
  dependsOn: DevPlan
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.10.5'
    displayName: 'Installing Terraform'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      commandOptions: '-backend-config="key=terraform-prod.tfstate"'
      backendServiceArm: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
      backendAzureRmResourceGroupName: 'stephen-blob'
      backendAzureRmStorageAccountName: 'stephenstorage'
      backendAzureRmContainerName: 'stephen-blob'
      backendAzureRmKey: 'terraform-prod.tfstate'
    displayName: 'Reinitialize Terraform'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-var-file=prod.tfvars'
      environmentServiceNameAzureRM: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
    displayName: 'Terraform apply'
