jobs:
- job: Plan
  pool:
    name: stephen-agent
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.10.5'
    displayName: 'Installing Terraform'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      commandOptions: '-backend-config="key=terraform-${{ parameters.env }}.tfstate"'
      backendServiceArm: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
      backendAzureRmResourceGroupName: 'stephen-blob'
      backendAzureRmStorageAccountName: 'stephenstorage'
      backendAzureRmContainerName: 'stephen-blob'
      backendAzureRmKey: 'terraform-${{ parameters.env }}.tfstate'
    displayName: 'Terraform init'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-var-file=${{ parameters.env }}.tfvars'
      environmentServiceNameAzureRM: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
    displayName: 'Terraform plan'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: 'terraform-build'
    displayName: 'Publish Terraform build artifacts'

- job: ManualValidation
  displayName: Wait for validation
  pool: server
  timeoutInMinutes: 1440
  steps:
  - task: ManualValidation@1
    timeoutInMinutes: 1440
    inputs:
      onTimeout: 'resume'

- job: Apply
  pool:
    name: stephen-agent
  dependsOn: 
  - Plan
  - ManualValidation
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.10.5'
    displayName: 'Installing Terraform'

  # - task: TerraformTaskV4@4
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'init'
  #     commandOptions: '-backend-config="key=terraform-${{ parameters.env }}.tfstate"'
  #     backendServiceArm: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
  #     backendAzureRmResourceGroupName: 'stephen-blob'
  #     backendAzureRmStorageAccountName: 'stephenstorage'
  #     backendAzureRmContainerName: 'stephen-blob'
  #     backendAzureRmKey: 'terraform-${{ parameters.env }}.tfstate'
  #   displayName: 'Reinitialize Terraform'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'terraform-build'
      path: '$(System.DefaultWorkingDirectory)'
    displayName: 'Download Terraform build artifacts'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-var-file=${{ parameters.env }}.tfvars'
      environmentServiceNameAzureRM: '2025-Jan-Platforms-Academy(d38fa016-777f-4647-bbc8-0aaf1933103c)'
    displayName: 'Terraform apply'
